export type LocationKind = "city" | "timezone";

export type Location = {
  slug: string;
  name: string;
  kind: LocationKind;
  region?: string;
  country: string;
  countryCode: string;
  iana: string;
  abbreviation?: string;
  aliases: string[];
  latitude?: number;
  longitude?: number;
  population?: string;
  currency?: string;
  dialingCode?: string;
  about: string;
  featured?: boolean;
};

function loc(entry: Location): Location {
  return entry;
}

export const LOCATIONS: Location[] = [
  loc({
    slug: "wa-seattle",
    name: "Seattle",
    kind: "city",
    region: "Washington",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: ["sea", "seattle wa", "seattle washington", "pacific time seattle"],
    latitude: 47.6062,
    longitude: -122.3321,
    population: "780,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about:
      "Seattle observes Pacific Time. Clocks move forward in March and back in November, so the gap with Hong Kong Time changes by one hour twice a year.",
    featured: true,
  }),
  loc({
    slug: "hkt",
    name: "Hong Kong Time",
    kind: "timezone",
    country: "Hong Kong",
    countryCode: "HK",
    iana: "Asia/Hong_Kong",
    abbreviation: "HKT",
    aliases: ["hong kong time", "hongkong", "gmt+8", "utc+8", "hkt timezone"],
    latitude: 22.3193,
    longitude: 114.1694,
    about:
      "Hong Kong Time (HKT) is a fixed UTC+8 zone. It does not use daylight saving, so the offset stays the same all year.",
    featured: true,
  }),
  loc({
    slug: "hk-hong-kong",
    name: "Hong Kong",
    kind: "city",
    country: "Hong Kong",
    countryCode: "HK",
    iana: "Asia/Hong_Kong",
    abbreviation: "HKT",
    aliases: ["hongkong", "kowloon", "victoria harbour"],
    latitude: 22.3193,
    longitude: 114.1694,
    population: "7.4 million",
    currency: "Hong Kong dollar (HKD)",
    dialingCode: "+852",
    about:
      "Hong Kong keeps Hong Kong Time year-round. There is no spring-forward or fall-back, which makes scheduling from DST regions easier to reason about in winter than in summer.",
    featured: true,
  }),
  loc({
    slug: "ny-new-york",
    name: "New York",
    kind: "city",
    region: "New York",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["nyc", "new york city", "manhattan", "eastern time"],
    latitude: 40.7128,
    longitude: -74.006,
    population: "8.3 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "New York City uses Eastern Time, with daylight saving from March to November.",
    featured: true,
  }),
  loc({
    slug: "ca-los-angeles",
    name: "Los Angeles",
    kind: "city",
    region: "California",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: ["la", "lax", "southern california"],
    latitude: 34.0522,
    longitude: -118.2437,
    population: "3.8 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Los Angeles shares Pacific Time with Seattle, San Francisco, and Vancouver’s winter offset.",
    featured: true,
  }),
  loc({
    slug: "ca-san-francisco",
    name: "San Francisco",
    kind: "city",
    region: "California",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: ["sf", "bay area"],
    latitude: 37.7749,
    longitude: -122.4194,
    population: "870,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "San Francisco follows Pacific Time with US daylight saving rules.",
  }),
  loc({
    slug: "il-chicago",
    name: "Chicago",
    kind: "city",
    region: "Illinois",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    aliases: ["chi", "central time"],
    latitude: 41.8781,
    longitude: -87.6298,
    population: "2.7 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Chicago is on Central Time, one hour ahead of Pacific Time.",
    featured: true,
  }),
  loc({
    slug: "tx-houston",
    name: "Houston",
    kind: "city",
    region: "Texas",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    aliases: ["iah"],
    latitude: 29.7604,
    longitude: -95.3698,
    population: "2.3 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Houston observes Central Time.",
  }),
  loc({
    slug: "tx-austin",
    name: "Austin",
    kind: "city",
    region: "Texas",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    aliases: [],
    latitude: 30.2672,
    longitude: -97.7431,
    population: "980,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Austin uses Central Time with US daylight saving.",
  }),
  loc({
    slug: "tx-dallas",
    name: "Dallas",
    kind: "city",
    region: "Texas",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    aliases: ["dfw"],
    latitude: 32.7767,
    longitude: -96.797,
    population: "1.3 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Dallas is in the US Central time zone.",
  }),
  loc({
    slug: "dc-washington",
    name: "Washington",
    kind: "city",
    region: "District of Columbia",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["dc", "washington dc"],
    latitude: 38.9072,
    longitude: -77.0369,
    population: "690,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Washington, D.C. follows Eastern Time.",
  }),
  loc({
    slug: "ma-boston",
    name: "Boston",
    kind: "city",
    region: "Massachusetts",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["bos"],
    latitude: 42.3601,
    longitude: -71.0589,
    population: "675,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Boston is on Eastern Time.",
  }),
  loc({
    slug: "fl-miami",
    name: "Miami",
    kind: "city",
    region: "Florida",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["mia"],
    latitude: 25.7617,
    longitude: -80.1918,
    population: "450,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Miami observes Eastern Time.",
  }),
  loc({
    slug: "ga-atlanta",
    name: "Atlanta",
    kind: "city",
    region: "Georgia",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["atl"],
    latitude: 33.749,
    longitude: -84.388,
    population: "500,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Atlanta uses Eastern Time.",
  }),
  loc({
    slug: "co-denver",
    name: "Denver",
    kind: "city",
    region: "Colorado",
    country: "United States",
    countryCode: "US",
    iana: "America/Denver",
    aliases: ["den", "mountain time"],
    latitude: 39.7392,
    longitude: -104.9903,
    population: "715,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Denver is on Mountain Time.",
    featured: true,
  }),
  loc({
    slug: "az-phoenix",
    name: "Phoenix",
    kind: "city",
    region: "Arizona",
    country: "United States",
    countryCode: "US",
    iana: "America/Phoenix",
    aliases: ["phx"],
    latitude: 33.4484,
    longitude: -112.074,
    population: "1.6 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about:
      "Most of Arizona stays on Mountain Standard Time all year and does not use daylight saving.",
  }),
  loc({
    slug: "or-portland",
    name: "Portland",
    kind: "city",
    region: "Oregon",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: ["pdx"],
    latitude: 45.5152,
    longitude: -122.6784,
    population: "650,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Portland, Oregon shares Pacific Time with Seattle.",
  }),
  loc({
    slug: "nv-las-vegas",
    name: "Las Vegas",
    kind: "city",
    region: "Nevada",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: ["vegas", "las vegas nv"],
    latitude: 36.1699,
    longitude: -115.1398,
    population: "660,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Las Vegas follows Pacific Time.",
  }),
  loc({
    slug: "mn-minneapolis",
    name: "Minneapolis",
    kind: "city",
    region: "Minnesota",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    aliases: ["msp"],
    latitude: 44.9778,
    longitude: -93.265,
    population: "425,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Minneapolis is on Central Time.",
  }),
  loc({
    slug: "hi-honolulu",
    name: "Honolulu",
    kind: "city",
    region: "Hawaii",
    country: "United States",
    countryCode: "US",
    iana: "Pacific/Honolulu",
    aliases: ["hnl", "hawaii"],
    latitude: 21.3069,
    longitude: -157.8583,
    population: "350,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Hawaii stays on Hawaii-Aleutian Standard Time and does not observe daylight saving.",
  }),
  loc({
    slug: "ak-anchorage",
    name: "Anchorage",
    kind: "city",
    region: "Alaska",
    country: "United States",
    countryCode: "US",
    iana: "America/Anchorage",
    aliases: ["alaska"],
    latitude: 61.2181,
    longitude: -149.9003,
    population: "290,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Anchorage uses Alaska Time with daylight saving.",
  }),
  loc({
    slug: "pa-philadelphia",
    name: "Philadelphia",
    kind: "city",
    region: "Pennsylvania",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    aliases: ["phl"],
    latitude: 39.9526,
    longitude: -75.1652,
    population: "1.6 million",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Philadelphia is on Eastern Time.",
  }),
  loc({
    slug: "wa-spokane",
    name: "Spokane",
    kind: "city",
    region: "Washington",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    aliases: [],
    latitude: 47.6588,
    longitude: -117.426,
    population: "230,000",
    currency: "US dollar (USD)",
    dialingCode: "+1",
    about: "Spokane follows Pacific Time, the same zone as Seattle.",
  }),
  loc({
    slug: "uk-london",
    name: "London",
    kind: "city",
    country: "United Kingdom",
    countryCode: "GB",
    iana: "Europe/London",
    aliases: ["ldn", "britain", "england", "gmt", "bst"],
    latitude: 51.5074,
    longitude: -0.1278,
    population: "8.9 million",
    currency: "Pound sterling (GBP)",
    dialingCode: "+44",
    about: "London uses Greenwich Mean Time in winter and British Summer Time in summer.",
    featured: true,
  }),
  loc({
    slug: "uk-manchester",
    name: "Manchester",
    kind: "city",
    country: "United Kingdom",
    countryCode: "GB",
    iana: "Europe/London",
    aliases: [],
    latitude: 53.4808,
    longitude: -2.2426,
    population: "550,000",
    currency: "Pound sterling (GBP)",
    dialingCode: "+44",
    about: "Manchester shares the United Kingdom’s GMT/BST schedule with London.",
  }),
  loc({
    slug: "ie-dublin",
    name: "Dublin",
    kind: "city",
    country: "Ireland",
    countryCode: "IE",
    iana: "Europe/Dublin",
    aliases: [],
    latitude: 53.3498,
    longitude: -6.2603,
    population: "590,000",
    currency: "Euro (EUR)",
    dialingCode: "+353",
    about: "Dublin follows Irish Standard Time in summer and GMT in winter.",
  }),
  loc({
    slug: "fr-paris",
    name: "Paris",
    kind: "city",
    country: "France",
    countryCode: "FR",
    iana: "Europe/Paris",
    aliases: ["cet", "cest"],
    latitude: 48.8566,
    longitude: 2.3522,
    population: "2.1 million",
    currency: "Euro (EUR)",
    dialingCode: "+33",
    about: "Paris is on Central European Time, one hour ahead of London.",
    featured: true,
  }),
  loc({
    slug: "de-berlin",
    name: "Berlin",
    kind: "city",
    country: "Germany",
    countryCode: "DE",
    iana: "Europe/Berlin",
    aliases: [],
    latitude: 52.52,
    longitude: 13.405,
    population: "3.7 million",
    currency: "Euro (EUR)",
    dialingCode: "+49",
    about: "Berlin uses Central European Time with EU daylight saving.",
    featured: true,
  }),
  loc({
    slug: "de-munich",
    name: "Munich",
    kind: "city",
    country: "Germany",
    countryCode: "DE",
    iana: "Europe/Berlin",
    aliases: ["munchen"],
    latitude: 48.1351,
    longitude: 11.582,
    population: "1.5 million",
    currency: "Euro (EUR)",
    dialingCode: "+49",
    about: "Munich shares Central European Time with Berlin.",
  }),
  loc({
    slug: "es-madrid",
    name: "Madrid",
    kind: "city",
    country: "Spain",
    countryCode: "ES",
    iana: "Europe/Madrid",
    aliases: [],
    latitude: 40.4168,
    longitude: -3.7038,
    population: "3.3 million",
    currency: "Euro (EUR)",
    dialingCode: "+34",
    about: "Madrid is on Central European Time.",
  }),
  loc({
    slug: "it-rome",
    name: "Rome",
    kind: "city",
    country: "Italy",
    countryCode: "IT",
    iana: "Europe/Rome",
    aliases: ["roma"],
    latitude: 41.9028,
    longitude: 12.4964,
    population: "2.8 million",
    currency: "Euro (EUR)",
    dialingCode: "+39",
    about: "Rome follows Central European Time.",
  }),
  loc({
    slug: "nl-amsterdam",
    name: "Amsterdam",
    kind: "city",
    country: "Netherlands",
    countryCode: "NL",
    iana: "Europe/Amsterdam",
    aliases: ["ams"],
    latitude: 52.3676,
    longitude: 4.9041,
    population: "920,000",
    currency: "Euro (EUR)",
    dialingCode: "+31",
    about: "Amsterdam is on Central European Time.",
  }),
  loc({
    slug: "ch-zurich",
    name: "Zurich",
    kind: "city",
    country: "Switzerland",
    countryCode: "CH",
    iana: "Europe/Zurich",
    aliases: ["zürich"],
    latitude: 47.3769,
    longitude: 8.5417,
    population: "430,000",
    currency: "Swiss franc (CHF)",
    dialingCode: "+41",
    about: "Zurich uses Central European Time.",
  }),
  loc({
    slug: "se-stockholm",
    name: "Stockholm",
    kind: "city",
    country: "Sweden",
    countryCode: "SE",
    iana: "Europe/Stockholm",
    aliases: [],
    latitude: 59.3293,
    longitude: 18.0686,
    population: "980,000",
    currency: "Swedish krona (SEK)",
    dialingCode: "+46",
    about: "Stockholm is on Central European Time.",
  }),
  loc({
    slug: "pl-warsaw",
    name: "Warsaw",
    kind: "city",
    country: "Poland",
    countryCode: "PL",
    iana: "Europe/Warsaw",
    aliases: [],
    latitude: 52.2297,
    longitude: 21.0122,
    population: "1.8 million",
    currency: "Polish zloty (PLN)",
    dialingCode: "+48",
    about: "Warsaw follows Central European Time.",
  }),
  loc({
    slug: "pt-lisbon",
    name: "Lisbon",
    kind: "city",
    country: "Portugal",
    countryCode: "PT",
    iana: "Europe/Lisbon",
    aliases: [],
    latitude: 38.7223,
    longitude: -9.1393,
    population: "550,000",
    currency: "Euro (EUR)",
    dialingCode: "+351",
    about: "Lisbon is on Western European Time, aligned with London rather than Madrid.",
  }),
  loc({
    slug: "gr-athens",
    name: "Athens",
    kind: "city",
    country: "Greece",
    countryCode: "GR",
    iana: "Europe/Athens",
    aliases: [],
    latitude: 37.9838,
    longitude: 23.7275,
    population: "640,000",
    currency: "Euro (EUR)",
    dialingCode: "+30",
    about: "Athens uses Eastern European Time.",
  }),
  loc({
    slug: "tr-istanbul",
    name: "Istanbul",
    kind: "city",
    country: "Turkey",
    countryCode: "TR",
    iana: "Europe/Istanbul",
    aliases: ["constantinople"],
    latitude: 41.0082,
    longitude: 28.9784,
    population: "15 million",
    currency: "Turkish lira (TRY)",
    dialingCode: "+90",
    about: "Istanbul stays on Turkey Time (UTC+3) all year.",
  }),
  loc({
    slug: "ru-moscow",
    name: "Moscow",
    kind: "city",
    country: "Russia",
    countryCode: "RU",
    iana: "Europe/Moscow",
    aliases: ["msk"],
    latitude: 55.7558,
    longitude: 37.6173,
    population: "13 million",
    currency: "Russian ruble (RUB)",
    dialingCode: "+7",
    about: "Moscow Time is a fixed UTC+3 zone with no daylight saving.",
  }),
  loc({
    slug: "ae-dubai",
    name: "Dubai",
    kind: "city",
    country: "United Arab Emirates",
    countryCode: "AE",
    iana: "Asia/Dubai",
    aliases: ["dxb", "uae"],
    latitude: 25.2048,
    longitude: 55.2708,
    population: "3.6 million",
    currency: "UAE dirham (AED)",
    dialingCode: "+971",
    about: "Dubai uses Gulf Standard Time (UTC+4) year-round.",
    featured: true,
  }),
  loc({
    slug: "il-tel-aviv",
    name: "Tel Aviv",
    kind: "city",
    country: "Israel",
    countryCode: "IL",
    iana: "Asia/Jerusalem",
    aliases: ["jerusalem"],
    latitude: 32.0853,
    longitude: 34.7818,
    population: "470,000",
    currency: "Israeli shekel (ILS)",
    dialingCode: "+972",
    about: "Tel Aviv follows Israel’s daylight saving calendar.",
  }),
  loc({
    slug: "eg-cairo",
    name: "Cairo",
    kind: "city",
    country: "Egypt",
    countryCode: "EG",
    iana: "Africa/Cairo",
    aliases: [],
    latitude: 30.0444,
    longitude: 31.2357,
    population: "10 million",
    currency: "Egyptian pound (EGP)",
    dialingCode: "+20",
    about: "Cairo uses Eastern European Time with Egypt’s DST schedule.",
  }),
  loc({
    slug: "za-johannesburg",
    name: "Johannesburg",
    kind: "city",
    country: "South Africa",
    countryCode: "ZA",
    iana: "Africa/Johannesburg",
    aliases: ["joburg", "jnb"],
    latitude: -26.2041,
    longitude: 28.0473,
    population: "5.6 million",
    currency: "South African rand (ZAR)",
    dialingCode: "+27",
    about: "Johannesburg stays on South Africa Standard Time (UTC+2).",
  }),
  loc({
    slug: "ng-lagos",
    name: "Lagos",
    kind: "city",
    country: "Nigeria",
    countryCode: "NG",
    iana: "Africa/Lagos",
    aliases: [],
    latitude: 6.5244,
    longitude: 3.3792,
    population: "15 million",
    currency: "Nigerian naira (NGN)",
    dialingCode: "+234",
    about: "Lagos uses West Africa Time (UTC+1) without daylight saving.",
  }),
  loc({
    slug: "in-mumbai",
    name: "Mumbai",
    kind: "city",
    country: "India",
    countryCode: "IN",
    iana: "Asia/Kolkata",
    aliases: ["bombay", "ist"],
    latitude: 19.076,
    longitude: 72.8777,
    population: "12.5 million",
    currency: "Indian rupee (INR)",
    dialingCode: "+91",
    about: "Mumbai uses India Standard Time (UTC+5:30) all year.",
    featured: true,
  }),
  loc({
    slug: "in-delhi",
    name: "New Delhi",
    kind: "city",
    country: "India",
    countryCode: "IN",
    iana: "Asia/Kolkata",
    aliases: ["delhi", "ndls"],
    latitude: 28.6139,
    longitude: 77.209,
    population: "32 million",
    currency: "Indian rupee (INR)",
    dialingCode: "+91",
    about: "New Delhi is on India Standard Time.",
  }),
  loc({
    slug: "in-bengaluru",
    name: "Bengaluru",
    kind: "city",
    country: "India",
    countryCode: "IN",
    iana: "Asia/Kolkata",
    aliases: ["bangalore", "blr"],
    latitude: 12.9716,
    longitude: 77.5946,
    population: "12 million",
    currency: "Indian rupee (INR)",
    dialingCode: "+91",
    about: "Bengaluru follows India Standard Time.",
  }),
  loc({
    slug: "sg-singapore",
    name: "Singapore",
    kind: "city",
    country: "Singapore",
    countryCode: "SG",
    iana: "Asia/Singapore",
    aliases: ["sgt", "sin"],
    latitude: 1.3521,
    longitude: 103.8198,
    population: "5.9 million",
    currency: "Singapore dollar (SGD)",
    dialingCode: "+65",
    about: "Singapore Time is UTC+8, the same offset as Hong Kong Time.",
    featured: true,
  }),
  loc({
    slug: "jp-tokyo",
    name: "Tokyo",
    kind: "city",
    country: "Japan",
    countryCode: "JP",
    iana: "Asia/Tokyo",
    aliases: ["tyo", "jst"],
    latitude: 35.6762,
    longitude: 139.6503,
    population: "14 million",
    currency: "Japanese yen (JPY)",
    dialingCode: "+81",
    about: "Tokyo uses Japan Standard Time (UTC+9) with no daylight saving.",
    featured: true,
  }),
  loc({
    slug: "jp-osaka",
    name: "Osaka",
    kind: "city",
    country: "Japan",
    countryCode: "JP",
    iana: "Asia/Tokyo",
    aliases: [],
    latitude: 34.6937,
    longitude: 135.5023,
    population: "2.7 million",
    currency: "Japanese yen (JPY)",
    dialingCode: "+81",
    about: "Osaka shares Japan Standard Time with Tokyo.",
  }),
  loc({
    slug: "kr-seoul",
    name: "Seoul",
    kind: "city",
    country: "South Korea",
    countryCode: "KR",
    iana: "Asia/Seoul",
    aliases: ["kst"],
    latitude: 37.5665,
    longitude: 126.978,
    population: "9.6 million",
    currency: "South Korean won (KRW)",
    dialingCode: "+82",
    about: "Seoul is on Korea Standard Time (UTC+9).",
    featured: true,
  }),
  loc({
    slug: "cn-beijing",
    name: "Beijing",
    kind: "city",
    country: "China",
    countryCode: "CN",
    iana: "Asia/Shanghai",
    aliases: ["peking", "cst china"],
    latitude: 39.9042,
    longitude: 116.4074,
    population: "21 million",
    currency: "Chinese yuan (CNY)",
    dialingCode: "+86",
    about: "Beijing uses China Standard Time (UTC+8).",
  }),
  loc({
    slug: "cn-shanghai",
    name: "Shanghai",
    kind: "city",
    country: "China",
    countryCode: "CN",
    iana: "Asia/Shanghai",
    aliases: ["pvg"],
    latitude: 31.2304,
    longitude: 121.4737,
    population: "24 million",
    currency: "Chinese yuan (CNY)",
    dialingCode: "+86",
    about: "Shanghai follows China Standard Time.",
  }),
  loc({
    slug: "tw-taipei",
    name: "Taipei",
    kind: "city",
    country: "Taiwan",
    countryCode: "TW",
    iana: "Asia/Taipei",
    aliases: [],
    latitude: 25.033,
    longitude: 121.5654,
    population: "2.5 million",
    currency: "New Taiwan dollar (TWD)",
    dialingCode: "+886",
    about: "Taipei is on UTC+8 year-round.",
  }),
  loc({
    slug: "th-bangkok",
    name: "Bangkok",
    kind: "city",
    country: "Thailand",
    countryCode: "TH",
    iana: "Asia/Bangkok",
    aliases: ["bkk"],
    latitude: 13.7563,
    longitude: 100.5018,
    population: "10 million",
    currency: "Thai baht (THB)",
    dialingCode: "+66",
    about: "Bangkok uses Indochina Time (UTC+7).",
  }),
  loc({
    slug: "vn-ho-chi-minh",
    name: "Ho Chi Minh City",
    kind: "city",
    country: "Vietnam",
    countryCode: "VN",
    iana: "Asia/Ho_Chi_Minh",
    aliases: ["saigon", "hcmc"],
    latitude: 10.8231,
    longitude: 106.6297,
    population: "9 million",
    currency: "Vietnamese dong (VND)",
    dialingCode: "+84",
    about: "Ho Chi Minh City is on Indochina Time (UTC+7).",
  }),
  loc({
    slug: "ph-manila",
    name: "Manila",
    kind: "city",
    country: "Philippines",
    countryCode: "PH",
    iana: "Asia/Manila",
    aliases: ["mnl"],
    latitude: 14.5995,
    longitude: 120.9842,
    population: "1.8 million",
    currency: "Philippine peso (PHP)",
    dialingCode: "+63",
    about: "Manila uses Philippine Time (UTC+8).",
  }),
  loc({
    slug: "id-jakarta",
    name: "Jakarta",
    kind: "city",
    country: "Indonesia",
    countryCode: "ID",
    iana: "Asia/Jakarta",
    aliases: ["cgk"],
    latitude: -6.2088,
    longitude: 106.8456,
    population: "10.6 million",
    currency: "Indonesian rupiah (IDR)",
    dialingCode: "+62",
    about: "Jakarta is on Western Indonesia Time (UTC+7).",
  }),
  loc({
    slug: "my-kuala-lumpur",
    name: "Kuala Lumpur",
    kind: "city",
    country: "Malaysia",
    countryCode: "MY",
    iana: "Asia/Kuala_Lumpur",
    aliases: ["kl", "kul"],
    latitude: 3.139,
    longitude: 101.6869,
    population: "1.8 million",
    currency: "Malaysian ringgit (MYR)",
    dialingCode: "+60",
    about: "Kuala Lumpur uses Malaysia Time (UTC+8).",
  }),
  loc({
    slug: "au-sydney",
    name: "Sydney",
    kind: "city",
    country: "Australia",
    countryCode: "AU",
    iana: "Australia/Sydney",
    aliases: ["syd", "aest", "aedt"],
    latitude: -33.8688,
    longitude: 151.2093,
    population: "5.3 million",
    currency: "Australian dollar (AUD)",
    dialingCode: "+61",
    about: "Sydney observes Australian Eastern Time, with daylight saving in the southern summer.",
    featured: true,
  }),
  loc({
    slug: "au-melbourne",
    name: "Melbourne",
    kind: "city",
    country: "Australia",
    countryCode: "AU",
    iana: "Australia/Melbourne",
    aliases: ["mel"],
    latitude: -37.8136,
    longitude: 144.9631,
    population: "5.1 million",
    currency: "Australian dollar (AUD)",
    dialingCode: "+61",
    about: "Melbourne shares Australian Eastern Time with Sydney.",
  }),
  loc({
    slug: "au-perth",
    name: "Perth",
    kind: "city",
    country: "Australia",
    countryCode: "AU",
    iana: "Australia/Perth",
    aliases: ["awst"],
    latitude: -31.9505,
    longitude: 115.8605,
    population: "2.1 million",
    currency: "Australian dollar (AUD)",
    dialingCode: "+61",
    about: "Perth stays on Australian Western Standard Time (UTC+8).",
  }),
  loc({
    slug: "nz-auckland",
    name: "Auckland",
    kind: "city",
    country: "New Zealand",
    countryCode: "NZ",
    iana: "Pacific/Auckland",
    aliases: ["akl", "nzst", "nzdt"],
    latitude: -36.8509,
    longitude: 174.7645,
    population: "1.7 million",
    currency: "New Zealand dollar (NZD)",
    dialingCode: "+64",
    about: "Auckland uses New Zealand Time with daylight saving in the southern summer.",
    featured: true,
  }),
  loc({
    slug: "ca-toronto",
    name: "Toronto",
    kind: "city",
    region: "Ontario",
    country: "Canada",
    countryCode: "CA",
    iana: "America/Toronto",
    aliases: ["yyz"],
    latitude: 43.6532,
    longitude: -79.3832,
    population: "2.9 million",
    currency: "Canadian dollar (CAD)",
    dialingCode: "+1",
    about: "Toronto is on Eastern Time, aligned with New York.",
    featured: true,
  }),
  loc({
    slug: "ca-vancouver",
    name: "Vancouver",
    kind: "city",
    region: "British Columbia",
    country: "Canada",
    countryCode: "CA",
    iana: "America/Vancouver",
    aliases: ["yvr"],
    latitude: 49.2827,
    longitude: -123.1207,
    population: "675,000",
    currency: "Canadian dollar (CAD)",
    dialingCode: "+1",
    about: "Vancouver follows Pacific Time, usually matching Seattle.",
  }),
  loc({
    slug: "ca-montreal",
    name: "Montreal",
    kind: "city",
    region: "Quebec",
    country: "Canada",
    countryCode: "CA",
    iana: "America/Toronto",
    aliases: ["montreal", "yul"],
    latitude: 45.5019,
    longitude: -73.5674,
    population: "1.8 million",
    currency: "Canadian dollar (CAD)",
    dialingCode: "+1",
    about: "Montreal is on Eastern Time.",
  }),
  loc({
    slug: "mx-mexico-city",
    name: "Mexico City",
    kind: "city",
    country: "Mexico",
    countryCode: "MX",
    iana: "America/Mexico_City",
    aliases: ["cdmx", "mexico"],
    latitude: 19.4326,
    longitude: -99.1332,
    population: "9.2 million",
    currency: "Mexican peso (MXN)",
    dialingCode: "+52",
    about: "Mexico City uses Central Time without seasonal clock changes.",
  }),
  loc({
    slug: "br-sao-paulo",
    name: "São Paulo",
    kind: "city",
    country: "Brazil",
    countryCode: "BR",
    iana: "America/Sao_Paulo",
    aliases: ["sao paulo", "gru"],
    latitude: -23.5505,
    longitude: -46.6333,
    population: "12 million",
    currency: "Brazilian real (BRL)",
    dialingCode: "+55",
    about: "São Paulo is on Brasília Time (UTC−3).",
    featured: true,
  }),
  loc({
    slug: "ar-buenos-aires",
    name: "Buenos Aires",
    kind: "city",
    country: "Argentina",
    countryCode: "AR",
    iana: "America/Argentina/Buenos_Aires",
    aliases: ["eze"],
    latitude: -34.6037,
    longitude: -58.3816,
    population: "3.1 million",
    currency: "Argentine peso (ARS)",
    dialingCode: "+54",
    about: "Buenos Aires stays on Argentina Time (UTC−3).",
  }),
  loc({
    slug: "cl-santiago",
    name: "Santiago",
    kind: "city",
    country: "Chile",
    countryCode: "CL",
    iana: "America/Santiago",
    aliases: [],
    latitude: -33.4489,
    longitude: -70.6693,
    population: "6.3 million",
    currency: "Chilean peso (CLP)",
    dialingCode: "+56",
    about: "Santiago observes Chile’s daylight saving calendar.",
  }),
  loc({
    slug: "co-bogota",
    name: "Bogotá",
    kind: "city",
    country: "Colombia",
    countryCode: "CO",
    iana: "America/Bogota",
    aliases: ["bogota"],
    latitude: 4.711,
    longitude: -74.0721,
    population: "8 million",
    currency: "Colombian peso (COP)",
    dialingCode: "+57",
    about: "Bogotá uses Colombia Time (UTC−5) all year.",
  }),
  loc({
    slug: "pe-lima",
    name: "Lima",
    kind: "city",
    country: "Peru",
    countryCode: "PE",
    iana: "America/Lima",
    aliases: [],
    latitude: -12.0464,
    longitude: -77.0428,
    population: "10 million",
    currency: "Peruvian sol (PEN)",
    dialingCode: "+51",
    about: "Lima stays on Peru Time (UTC−5).",
  }),
  loc({
    slug: "utc",
    name: "UTC",
    kind: "timezone",
    country: "Worldwide",
    countryCode: "UN",
    iana: "UTC",
    abbreviation: "UTC",
    aliases: ["gmt", "zulu", "coordinated universal time", "z"],
    about:
      "Coordinated Universal Time is the reference for every civil offset on this site. It does not observe daylight saving.",
    featured: true,
  }),
  loc({
    slug: "gmt",
    name: "GMT",
    kind: "timezone",
    country: "Worldwide",
    countryCode: "UN",
    iana: "Etc/GMT",
    abbreviation: "GMT",
    aliases: ["greenwich", "greenwich mean time"],
    about: "Greenwich Mean Time matches UTC for civil conversion on Hourbridge.",
  }),
  loc({
    slug: "pst",
    name: "Pacific Time",
    kind: "timezone",
    country: "United States",
    countryCode: "US",
    iana: "America/Los_Angeles",
    abbreviation: "PT",
    aliases: ["pdt", "pacific standard time", "pacific daylight time"],
    about:
      "Pacific Time covers Seattle, Los Angeles, and San Francisco. The abbreviation switches between PST and PDT.",
    featured: true,
  }),
  loc({
    slug: "est",
    name: "Eastern Time",
    kind: "timezone",
    country: "United States",
    countryCode: "US",
    iana: "America/New_York",
    abbreviation: "ET",
    aliases: ["edt", "eastern standard time", "eastern daylight time"],
    about: "Eastern Time is used in New York, Washington, D.C., Miami, and Toronto.",
    featured: true,
  }),
  loc({
    slug: "cst",
    name: "Central Time",
    kind: "timezone",
    country: "United States",
    countryCode: "US",
    iana: "America/Chicago",
    abbreviation: "CT",
    aliases: ["cdt", "central standard time", "central daylight time"],
    about: "US Central Time covers Chicago, Houston, Dallas, and Mexico City’s winter offset.",
  }),
  loc({
    slug: "mst",
    name: "Mountain Time",
    kind: "timezone",
    country: "United States",
    countryCode: "US",
    iana: "America/Denver",
    abbreviation: "MT",
    aliases: ["mdt", "mountain standard time"],
    about: "Mountain Time is used in Denver. Arizona generally stays on standard time.",
  }),
  loc({
    slug: "ist",
    name: "India Standard Time",
    kind: "timezone",
    country: "India",
    countryCode: "IN",
    iana: "Asia/Kolkata",
    abbreviation: "IST",
    aliases: ["india time", "indian standard time"],
    about: "India Standard Time is UTC+5:30 and does not change with the seasons.",
  }),
  loc({
    slug: "jst",
    name: "Japan Standard Time",
    kind: "timezone",
    country: "Japan",
    countryCode: "JP",
    iana: "Asia/Tokyo",
    abbreviation: "JST",
    aliases: ["japan time"],
    about: "Japan Standard Time is UTC+9 all year.",
  }),
  loc({
    slug: "cet",
    name: "Central European Time",
    kind: "timezone",
    country: "Europe",
    countryCode: "EU",
    iana: "Europe/Paris",
    abbreviation: "CET",
    aliases: ["cest", "central european summer time"],
    about: "CET/CEST is used from Paris and Berlin to Madrid and Rome.",
  }),
  loc({
    slug: "aest",
    name: "Australian Eastern Time",
    kind: "timezone",
    country: "Australia",
    countryCode: "AU",
    iana: "Australia/Sydney",
    abbreviation: "AET",
    aliases: ["aedt", "australian eastern standard time"],
    about: "Australian Eastern Time covers Sydney and Melbourne, with daylight saving in summer.",
  }),
  loc({
    slug: "sgt",
    name: "Singapore Time",
    kind: "timezone",
    country: "Singapore",
    countryCode: "SG",
    iana: "Asia/Singapore",
    abbreviation: "SGT",
    aliases: ["singapore time"],
    about: "Singapore Time is a fixed UTC+8 zone.",
  }),
];

const bySlug = new Map(LOCATIONS.map((location) => [location.slug, location]));

export const HUB_SLUGS = [
  "wa-seattle",
  "hkt",
  "hk-hong-kong",
  "ny-new-york",
  "uk-london",
  "ca-los-angeles",
  "jp-tokyo",
  "il-chicago",
  "au-sydney",
  "ae-dubai",
  "sg-singapore",
  "fr-paris",
  "in-mumbai",
  "ca-toronto",
  "de-berlin",
  "br-sao-paulo",
  "nz-auckland",
  "kr-seoul",
  "utc",
  "pst",
  "est",
] as const;

export const POPULAR_PAIRS: [string, string][] = [
  ["wa-seattle", "hkt"],
  ["ny-new-york", "uk-london"],
  ["ca-los-angeles", "jp-tokyo"],
  ["il-chicago", "uk-london"],
  ["uk-london", "hkt"],
  ["ny-new-york", "hkt"],
  ["wa-seattle", "jp-tokyo"],
  ["ca-los-angeles", "uk-london"],
  ["sg-singapore", "uk-london"],
  ["in-mumbai", "ny-new-york"],
  ["au-sydney", "ca-los-angeles"],
  ["ae-dubai", "uk-london"],
  ["fr-paris", "ny-new-york"],
  ["ca-toronto", "uk-london"],
  ["de-berlin", "ny-new-york"],
  ["hk-hong-kong", "ny-new-york"],
  ["wa-seattle", "uk-london"],
  ["jp-tokyo", "ny-new-york"],
];

export function getLocation(slug: string) {
  return bySlug.get(slug) ?? null;
}

export function requireLocation(slug: string) {
  const location = getLocation(slug);
  if (!location) throw new Error(`Unknown location: ${slug}`);
  return location;
}

export function locationFullName(location: Location) {
  if (location.kind === "timezone") {
    return location.abbreviation
      ? `${location.name} (${location.abbreviation})`
      : location.name;
  }
  if (location.region) {
    return `${location.name}, ${location.region}, ${location.country}`;
  }
  return `${location.name}, ${location.country}`;
}

export function locationShortPlace(location: Location) {
  if (location.kind === "timezone") return location.name;
  if (location.region) return `${location.name}, ${location.region}`;
  return location.name;
}

export function converterSlug(from: Location, to: Location) {
  return `${from.slug}-to-${to.slug}`;
}

export function parseConverterSlug(slug: string) {
  const idx = slug.indexOf("-to-");
  if (idx <= 0) return null;
  const from = getLocation(slug.slice(0, idx));
  const to = getLocation(slug.slice(idx + 4));
  if (!from || !to || from.slug === to.slug) return null;
  return { from, to };
}

export function searchLocations(query: string, limit = 12) {
  const needle = query.trim().toLowerCase();
  if (!needle) {
    return LOCATIONS.filter((location) => location.featured).slice(0, limit);
  }
  const scored = LOCATIONS.map((location) => {
    const hay = [
      location.slug,
      location.name,
      location.region ?? "",
      location.country,
      location.abbreviation ?? "",
      location.iana,
      ...location.aliases,
    ]
      .join(" ")
      .toLowerCase();
    let score = 0;
    if (location.slug === needle || location.abbreviation?.toLowerCase() === needle) score = 100;
    else if (location.name.toLowerCase() === needle) score = 90;
    else if (location.name.toLowerCase().startsWith(needle)) score = 80;
    else if (hay.includes(needle)) score = 50;
    else score = -1;
    if (location.featured && score > 0) score += 5;
    return { location, score };
  })
    .filter((row) => row.score >= 0)
    .sort((a, b) => b.score - a.score || a.location.name.localeCompare(b.location.name));
  return scored.slice(0, limit).map((row) => row.location);
}

export function getStaticConverterSlugs() {
  const slugs = new Set<string>();
  for (const [fromSlug, toSlug] of POPULAR_PAIRS) {
    slugs.add(`${fromSlug}-to-${toSlug}`);
    slugs.add(`${toSlug}-to-${fromSlug}`);
  }
  for (const fromSlug of HUB_SLUGS) {
    for (const toSlug of HUB_SLUGS) {
      if (fromSlug === toSlug) continue;
      slugs.add(`${fromSlug}-to-${toSlug}`);
    }
  }
  return [...slugs];
}

export function relatedDestinations(from: Location, to: Location, limit = 8) {
  const hubs = HUB_SLUGS.map(getLocation).filter(Boolean) as Location[];
  return hubs
    .filter((hub) => hub.slug !== from.slug && hub.slug !== to.slug)
    .slice(0, limit);
}

export function citiesUsingZone(iana: string) {
  return LOCATIONS.filter((location) => location.kind === "city" && location.iana === iana);
}

export function uniqueIanaZones() {
  const seen = new Map<string, Location>();
  for (const location of LOCATIONS) {
    if (!seen.has(location.iana)) seen.set(location.iana, location);
  }
  return [...seen.values()].sort((a, b) => a.iana.localeCompare(b.iana));
}

export function groupedCities() {
  const groups = new Map<string, Location[]>();
  for (const location of LOCATIONS.filter((item) => item.kind === "city")) {
    const key = location.country;
    const list = groups.get(key) ?? [];
    list.push(location);
    groups.set(key, list);
  }
  return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b));
}
